title: "Manmatha Roy"
email: "reach.manmatha@gmail.com"
description: ""
baseurl: "" # leave empty if deploying to root
url: "https://manmatha-roy.github.io" # change to your repo URL
markdown: kramdown
plugins: [jekyll-feed]

exclude:
  - "*.sh"
  - "scripts/"
